name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build webui module
      run: mvn clean install -pl src/webui -am

    - name: Run tests for webui
      run: mvn test -pl src/webui

    - name: Upload webui WAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: webui-war
        path: src/webui/target/*.war
