name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build webui module
      run: mvn clean install -pl src/webui -am

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Upload WAR to S3
      run: |
        aws s3 mb s3://cbsa-deployment-bucket --region ${{ secrets.AWS_REGION }} || true
        aws s3 cp src/webui/target/*.war s3://cbsa-deployment-bucket/webui-v1.war

    - name: Create EB application version
      run: |
        aws elasticbeanstalk create-application-version \
          --application-name cbsa-webui \
          --version-label v1 \
          --source-bundle S3Bucket=cbsa-deployment-bucket,S3Key=webui-v1.war

    - name: Update EB environment
      run: |
        aws elasticbeanstalk update-environment \
          --environment-name cbsa-webui-env \
          --version-label v1
